apiVersion: v1
kind: Pod
metadata:
  labels:
    app: aks-ssh
  name: aks-ssh
spec:
  containers:
  - image: prasenforu/ssh-client
    imagePullPolicy: Always
    name: aks-ssh
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 10; done;" ]
  nodeSelector:
    beta.kubernetes.io/os: linux
