{
 "title": "⭐️ Kubernetes PoD Monitoring",
 "description": "Kubernetes PoD monitoring using prometheus.",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Node", "query": "label_values(node)" },
   { "name": "Project", "query": "label_values(namespace)" },
   {
    "name": "PoD",
    "query": "label_values(kube_pod_info{namespace=\"$Project\"},pod)"
   },
   {
    "name": "PoD_Node",
    "query": "label_values(kube_pod_info{namespace=\"$Project\",pod=\"$PoD\"},node)"
   },
   {
    "name": "Con_Id",
    "query": "label_values(kube_pod_container_info{namespace=\"$Project\",pod=\"$PoD\"},container_id)"
   },
   {
    "name": "PoD_Host",
    "query": "label_values(kube_pod_info{namespace=\"$Project\",pod=\"$PoD\"},host_ip)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100))\n+\navg(100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\",instance!=\"\"}[5m])) * 100)) "
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100\n+\n(sum(windows_cs_physical_memory_bytes{instance!=\"\"}) - sum(windows_os_physical_memory_free_bytes{instance!=\"\"})) / \nsum(windows_cs_physical_memory_bytes{instance!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk-1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device=~\"/dev/.*\"}) - sum(node_filesystem_free_bytes{device=~\"/dev/.*\"}) ) / sum(node_filesystem_size_bytes{device=~\"/dev/.*\"}) * 100\n+\n(sum(windows_logical_disk_size_bytes {instance!=\"\",volume=\"C:\"}) - sum(windows_logical_disk_free_bytes {instance!=\"\",volume=\"C:\"})) / sum(windows_logical_disk_size_bytes {instance!=\"\",volume=\"C:\"}) * 100"
    }
   ]
  },
  {
   "title": "Kubernetes Core Services",
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(avg by (job) (up{job=~\"kubelet|apiserver\"}))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sort(avg by (container)  (kube_pod_container_status_running{container=~\"kube-controller-manager|kube-scheduler|etcd|coredns\",namespace=\"kube-system\"}))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "PoD Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kubelet_running_pod_count)", "legendFormat": "Running " }
   ]
  },
  {
   "title": "Container Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count)",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD Capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\"} == 1)",
     "legendFormat": "Running "
    }
   ]
  },
  { "title": "PoD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pods Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sort_desc (sum (container_memory_usage_bytes{image!=\"\",pod=\"$PoD\",namespace=~\"^$Project$\",instance=~\"^$Node$\"}) by (pod,instance))",
     "legendFormat": "{{ pod }}  ( {{ instance }} )"
    },
    {
     "expr": "sort_desc (sum (windows_container_memory_usage_commit_bytes{container_id=~\"$Con_Id\"}) by (container_id))",
     "legendFormat": "{{ pod }}  ( {{ instance }} )"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=~\"$PoD\",namespace=~\"^$Project$\",instance=~\"^$Node$\"}[2m])) by (pod,instance)",
     "legendFormat": "{{ pod }}  ({{ instance }}  )"
    },
    {
     "expr": "sum (rate (windows_container_cpu_usage_seconds_total{container_id=~\"$Con_Id\"}[2m])) by (container_id)",
     "legendFormat": "{{ \"$PoD\" }}  ({{ instance }}  )"
    }
   ]
  },
  {
   "title": "Pods logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{pod=\"$PoD\"} "
    },
    {
     "expr": "{instance=\"$PoD\"} "
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod)",
     "legendFormat": "IN"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod)",
     "legendFormat": "OUT"
    },
    {
     "expr": "sum (rate (windows_container_network_receive_bytes_total{container_id=~\"$Con_Id\"}[2m])) by (container_id)",
     "legendFormat": "IN"
    },
    {
     "expr": "- sum (rate (windows_container_network_transmit_bytes_total{container_id=~\"$Con_Id\"}[2m])) by (container_id)",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{pod=~\"$PoD\"}",
       "legendFormat": "current  "
      },
      {
       "expr": "jvm_threads_daemon{pod=~\"$PoD\"}",
       "legendFormat": "daemon "
      },
      {
       "expr": "jvm_threads_deadlocked {pod=~\"$PoD\"}",
       "legendFormat": "deadlock"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor {pod=~\"$PoD\"}",
       "legendFormat": "deadlock monitor"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{pod=~\"$PoD\"}",
       "legendFormat": "{{area}} memory "
      }
     ]
    },
    {
     "title": "GC time / 1 min. rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$PoD\"}[1m])",
       "legendFormat": "{{gc}} "
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{pod=~\"$PoD\"}",
       "legendFormat": "{{gc}} "
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{pod=~\"$PoD\"}",
       "legendFormat": "loaded "
      }
     ]
    }
   ]
  },
  {
   "title": "MQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages in Queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_messages{instance=~\"$PoD\",queue!=\"\"}",
       "legendFormat": "Queue ( {{queue}} )"
      }
     ]
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Node CPU ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",instance=~\"$PoD_Node\"}[5m])) * 100))"
    },
    {
     "expr": "avg(100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\",instance=~\"$PoD_Host:9100\"}[5m])) * 100)) "
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((windows_cs_physical_memory_bytes{instance=\"$PoD_Host:9100\"}) - (windows_os_physical_memory_free_bytes{instance=\"$PoD_Host:9100\"})) / (windows_cs_physical_memory_bytes{instance=\"$PoD_Host:9100\"}) * 100"
    },
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$PoD_Node\"}) - ((node_memory_MemFree_bytes{instance=~\"$PoD_Node\"}) + (node_memory_Buffers_bytes{instance=~\"$PoD_Node\"}) + (node_memory_Cached_bytes{instance=~\"$PoD_Node\"}))) / (node_memory_MemTotal_bytes{instance=~\"$PoD_Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Disk1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes {job=\"node-exporter\",device=\"/dev/sda1\",instance=~\"$PoD_Node\",mountpoint=\"/\"}) - (node_filesystem_free_bytes {job=\"node-exporter\",device=\"/dev/sda1\",instance=~\"$PoD_Node\",mountpoint=\"/\"})) / (node_filesystem_size_bytes {job=\"node-exporter\",device=\"/dev/sda1\",instance=~\"$PoD_Node\",mountpoint=\"/\"}\r\n) * 100"
    },
    {
     "expr": "((windows_logical_disk_size_bytes {instance=\"$PoD_Host:9100\",volume=\"C:\"}) - (windows_logical_disk_free_bytes {instance=\"$PoD_Host:9100\",volume=\"C:\"})) / (windows_logical_disk_size_bytes {instance=\"$PoD_Host:9100\",volume=\"C:\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 27 },
   "options": { "content": "    $PoD_Node\n" },
   "content": "    $PoD_Node\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Container ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count {kubernetes_io_hostname=\"$PoD_Node\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_hostname=\"$PoD_Node\"} ",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{node=\"$PoD_Node\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$PoD_Node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "usage"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{instance=~\"$PoD_Host:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Node Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$PoD_Node\"}) - ((node_memory_MemFree_bytes{instance=~\"$PoD_Node\"}) + (node_memory_Buffers_bytes{instance=~\"$PoD_Node\"}) + (node_memory_Cached_bytes{instance=~\"$PoD_Node\"}))) ",
     "legendFormat": "usage"
    },
    {
     "expr": "(node_memory_Buffers_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "buffers"
    },
    {
     "expr": "(node_memory_Cached_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "cached"
    },
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "total"
    },
    {
     "expr": "(windows_cs_physical_memory_bytes{instance=\"$PoD_Host:9100\"}) - (windows_os_physical_memory_free_bytes{instance=\"$PoD_Host:9100\"}) ",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Node load usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 1"
    },
    {
     "expr": "sum(node_load5{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 5"
    },
    {
     "expr": "sum(node_load15{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 15"
    },
    {
     "expr": "avg_over_time(windows_system_processor_queue_length {instance=~\"$PoD_Host:9100\"}[1m])",
     "legendFormat": "Load 1"
    },
    {
     "expr": "avg_over_time(windows_system_processor_queue_length {instance=~\"$PoD_Host:9100\"}[5m])",
     "legendFormat": "Load 5"
    },
    {
     "expr": "avg_over_time(windows_system_processor_queue_length {instance=~\"$PoD_Host:9100\"}[15m])",
     "legendFormat": "Load 15"
    }
   ]
  },
  {
   "title": "Node Disk usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{instance=\"$PoD_Node\"}[5m])) ",
     "legendFormat": "IO time"
    },
    {
     "expr": "sum(rate(windows_logical_disk_read_bytes_total{instance=\"$PoD_Host:9100\",volume=\"C:\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(windows_logical_disk_write_bytes_total{instance=\"$PoD_Host:9100\",volume=\"C:\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(windows_logical_disk_free_bytes{instance=\"$PoD_Host:9100\",volume=\"C:\"}) ",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(windows_logical_disk_size_bytes{instance=\"$PoD_Host:9100\",volume=\"C:\"}) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$PoD_Node\"}) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_free_bytes{instance=\"$PoD_Node\"}) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Node Network usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum (rate (node_network_transmit_bytes_total{instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "node_out"
    },
    {
     "expr": "sum (rate (node_network_transmit_bytes_total{device=\"eth0\",instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "eth0 out"
    },
    {
     "expr": "sum (rate (windows_net_bytes_sent_total{instance=\"$PoD_Host:9100\"}[5m]))",
     "legendFormat": "node_out"
    },
    {
     "expr": "- sum (rate (windows_net_bytes_received_total{instance=\"$PoD_Host:9100\"}[5m]))",
     "legendFormat": "eth0 out"
    }
   ]
  }
 ]
}